### ISSUE TITLE
Errors due to BLINCUSUSER and other variables not getting replaced

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/blincus#20]
Ive been getting some errors when trying to execute shells inside my blincus-managed incus containers because the `~/.config/blincus/template`s didnt get customized with my user configurations upon install. Maybe the "personalize" function on [initialize.sh](https://github.com/ublue-os/blincus/blob/main/src/initialize.sh) should be uncommented? Or it should be moved to the installation script instead of the main blincus one

**Comment by bketelsen** [comment]
the next release moves the customization to JIT so it won't be accidentally skipped. thanks for the report.
